// examples/react/src/EventLaunchApp.tsx
import { useEffect, useRef, useState, type FormEvent } from "react";
import { formEvent, nodeEvent, stages, type SerializedStagesState, type StagesChange, type StagesController } from "@stages/core";
import { StagesField, useStages, useStagesCollection, useStagesWizard } from "@stages/react";
import {
  EVENT_LAUNCH_AGENDA_ADDRESS,
  EVENT_LAUNCH_STORAGE_KEY,
  EVENT_LAUNCH_TICKETS_ADDRESS,
  EVENT_LAUNCH_WIZARD_ADDRESS,
  clearEventLaunchDraft,
  createAgendaItem,
  createEventLaunchSchema,
  createTicketTier,
  debounceDraftSave,
  defaultEventLaunchContext,
  defaultEventLaunchValue,
  eventLaunchValueCodec,
  readEventLaunchDraft,
  saveEventLaunchDraft,
  smokeTestValue,
  type AgendaItem,
  type EventLaunchContext,
  type EventLaunchValue,
} from "../../shared/event-launch/index.js";
import { eventLaunchReactFields } from "./fields.js";

type Controller = StagesController<EventLaunchValue, typeof eventLaunchReactFields, EventLaunchContext>;
const schema = createEventLaunchSchema();
const stageCopy: Readonly<Record<string, readonly [string, string]>> = {
  basics: ["Event basics", "Start with the public identity, timing, delivery, and registration model."],
  venue: ["Venue", "Capture the place and the practical details attendees need."],
  streaming: ["Streaming", "Configure the attendee link and recording consent."],
  agenda: ["Agenda", "Mix sessions, workshops, and breaks while preserving stable row identity."],
  tickets: ["Ticket tiers", "Set paid tiers and keep the totals within venue capacity."],
  compliance: ["Data processing", "This stage is inserted by external organization context."],
  review: ["Review and publish", "Confirm the final details before producing the application-owned payload."],
};

function Field({ path }: { readonly path: readonly (string | number)[] }) {
  return <StagesField controller={useController()} path={path} />;
}

const ControllerContext = (() => {
  let current: Controller | undefined;
  return {
    set(value: Controller) { current = value; },
    get() { if (current === undefined) throw new Error("Event Launch controller is unavailable."); return current; },
  };
})();
function useController(): Controller { return ControllerContext.get(); }

function BasicsStage() { return <div className="field-grid">
  <Field path={["launch", "basics", "identity", "title"]} /><Field path={["launch", "basics", "identity", "slug"]} />
  <Field path={["launch", "basics", "identity", "description"]} /><Field path={["launch", "basics", "schedule", "startsAt"]} />
  <Field path={["launch", "basics", "schedule", "endsAt"]} /><Field path={["launch", "basics", "schedule", "timezone"]} />
  <Field path={["launch", "basics", "deliveryMode"]} /><Field path={["launch", "basics", "accessModel"]} />
</div>; }
function VenueStage() { return <div className="field-grid"><Field path={["launch", "venue", "name"]} /><Field path={["launch", "venue", "capacity"]} /><Field path={["launch", "venue", "address", "street"]} /><Field path={["launch", "venue", "address", "city"]} /><Field path={["launch", "venue", "address", "country"]} /><Field path={["launch", "venue", "accessibilityNotes"]} /></div>; }
function StreamingStage() { return <div className="field-grid"><Field path={["launch", "streaming", "platform"]} /><Field path={["launch", "streaming", "url"]} /><Field path={["launch", "streaming", "recordEvent"]} /><Field path={["launch", "streaming", "recordingConsent"]} /></div>; }

function AgendaStage({ controller }: { readonly controller: Controller }) {
  const collection = useStagesCollection(controller, ["launch", "agenda", "items"] as const);
  const nextId = useRef(10);
  const dispatchRow = (name: string, address: typeof collection.items[number]["address"], payload?: unknown) => controller.dispatch(nodeEvent(name, address, { payload }));
  const add = (kind: AgendaItem["kind"]) => { collection.add(createAgendaItem(kind, `agenda-${kind}-${nextId.current}`)); nextId.current += 1; };
  const sortBreaksLast = () => {
    const order = collection.items.map((item, index) => ({ index, isBreak: item.value.kind === "break" })).sort((a, b) => Number(a.isBreak) - Number(b.isBreak)).map((entry) => entry.index);
    controller.dispatch(nodeEvent("collection:sort", EVENT_LAUNCH_AGENDA_ADDRESS, { payload: { order } }));
  };
  return <>
    <div className="collection-toolbar"><div><strong>{collection.items.length} agenda items</strong><p className="field-description">Collection controls dispatch standard node events.</p></div><div className="row-actions"><button type="button" disabled={!collection.canAdd} onClick={() => add("session")}>Add session</button><button type="button" disabled={!collection.canAdd} onClick={() => add("workshop")}>Add workshop</button><button type="button" disabled={!collection.canAdd} onClick={() => add("break")}>Add break</button><button type="button" onClick={sortBreaksLast}>Sort breaks last</button></div></div>
    <ol className="collection-list">{collection.items.map((item) => <li className="collection-row" key={item.key} data-testid={`agenda-row-${item.value.id}`}>
      <div className="row-header"><span className="row-kind">{item.value.kind}</span><span className="row-key">{item.key}</span></div>
      <div className="field-grid">
        {item.value.kind === "break" ? <Field path={["launch", "agenda", "items", item.index, "label"]} /> : <><Field path={["launch", "agenda", "items", item.index, "title"]} /><Field path={["launch", "agenda", "items", item.index, item.value.kind === "session" ? "speaker" : "facilitator"]} /></>}
        <Field path={["launch", "agenda", "items", item.index, "durationMinutes"]} />
        {item.value.kind === "workshop" && <Field path={["launch", "agenda", "items", item.index, "capacity"]} />}
      </div>
      <div className="row-actions"><button type="button" className="quiet" disabled={!item.canMovePrevious} onClick={() => item.moveTo(item.index - 1)}>Move up</button><button type="button" className="quiet" disabled={!item.canMoveNext} onClick={() => item.moveTo(item.index + 1)}>Move down</button><button type="button" className="quiet" disabled={!collection.canAdd} onClick={() => { const value = item.value; collection.add({ ...value, id: `agenda-${value.kind}-${nextId.current}` } as AgendaItem); nextId.current += 1; }}>Duplicate</button>{item.value.kind === "session" && <button type="button" className="quiet" onClick={() => { const value = item.value; if (value.kind === "session") dispatchRow("collection:replace", item.address, { value: { id: value.id, kind: "workshop", title: value.title, facilitator: value.speaker, durationMinutes: value.durationMinutes, capacity: 30 } }); }}>Convert to workshop</button>}<button type="button" className="quiet danger" disabled={!item.canRemove} onClick={item.remove}>Remove</button></div>
    </li>)}</ol>
  </>;
}

function TicketsStage({ controller, value }: { readonly controller: Controller; readonly value: EventLaunchValue }) {
  const collection = useStagesCollection(controller, ["launch", "tickets", "tiers"] as const);
  const nextId = useRef(10);
  const sold = value.launch.tickets.tiers.reduce((sum, tier) => sum + (tier.quantity ?? 0), 0);
  const gross = value.launch.tickets.tiers.reduce((sum, tier) => sum + (tier.quantity ?? 0) * (tier.price ?? 0), 0);
  return <><div className="field-grid"><Field path={["launch", "tickets", "currency"]} /></div><p><strong>{Math.max(0, (value.launch.venue.capacity ?? 0) - sold)}</strong> places remain · gross potential <strong>{new Intl.NumberFormat(defaultEventLaunchContext.locale, { style: "currency", currency: value.launch.tickets.currency }).format(gross)}</strong></p><div className="collection-toolbar"><strong>{collection.items.length} ticket tiers</strong><button type="button" disabled={!collection.canAdd} onClick={() => { collection.add(createTicketTier(`ticket-${nextId.current}`)); nextId.current += 1; }}>Add tier</button></div><ol className="collection-list">{collection.items.map((item) => <li className="collection-row" key={item.key} data-testid={`ticket-row-${item.value.id}`}><div className="row-header"><span className="row-kind">Ticket</span><span className="row-key">{item.key}</span></div><div className="field-grid"><Field path={["launch", "tickets", "tiers", item.index, "name"]} /><Field path={["launch", "tickets", "tiers", item.index, "price"]} /><Field path={["launch", "tickets", "tiers", item.index, "quantity"]} /></div><div className="row-actions"><button type="button" className="quiet" disabled={!item.canMovePrevious} onClick={() => item.moveTo(item.index - 1)}>Move up</button><button type="button" className="quiet" disabled={!item.canMoveNext} onClick={() => item.moveTo(item.index + 1)}>Move down</button><button type="button" className="quiet danger" disabled={!item.canRemove} onClick={item.remove}>Remove</button></div></li>)}</ol></>;
}

function ReviewStage({ value }: { readonly value: EventLaunchValue }) { return <><dl className="summary-list"><div><dt>Event</dt><dd>{value.launch.basics.identity.title}</dd></div><div><dt>Delivery</dt><dd>{value.launch.basics.deliveryMode}</dd></div><div><dt>Agenda</dt><dd>{value.launch.agenda.items.length} items</dd></div><div><dt>Registration</dt><dd>{value.launch.basics.accessModel}</dd></div></dl><div className="field-grid"><Field path={["launch", "review", "termsAccepted"]} /><Field path={["launch", "review", "confirmation"]} /></div></>; }

interface InnerProps { readonly adapter: string; readonly initialState: SerializedStagesState | undefined; readonly onResume: (state: SerializedStagesState) => void; }
function EventLaunchInner({ adapter, initialState, onResume }: InnerProps) {
  const [context, setContext] = useState(defaultEventLaunchContext);
  const [message, setMessage] = useState("");
  const [lastChange, setLastChange] = useState<StagesChange<EventLaunchValue>>();
  const [published, setPublished] = useState<EventLaunchValue>();
  const formRef = useRef<HTMLFormElement>(null);
  const { controller, snapshot } = useStages(() => {
    let created: Controller;
    const onChange = (change: StagesChange<EventLaunchValue>) => { created.update({ value: change.value }); setLastChange(change); };
    created = initialState === undefined
      ? stages<EventLaunchValue, typeof eventLaunchReactFields, EventLaunchContext>({ schema, fields: eventLaunchReactFields, value: structuredClone(defaultEventLaunchValue), context, codec: eventLaunchValueCodec, onChange, validationFailureIssue: ({ validatorId }) => ({ message: `The ${validatorId} check could not finish. Try again.`, meta: { recoverable: true } }) })
      : stages<EventLaunchValue, typeof eventLaunchReactFields, EventLaunchContext>({ schema, fields: eventLaunchReactFields, state: initialState, context, codec: eventLaunchValueCodec, onChange, validationFailureIssue: ({ validatorId }) => ({ message: `The ${validatorId} check could not finish. Try again.`, meta: { recoverable: true } }) });
    return created;
  }, { context });
  ControllerContext.set(controller);
  const wizard = useStagesWizard(controller, ["launch"]);
  const currentIndex = wizard.stages.findIndex((stage) => stage.active);
  const active = wizard.stages[currentIndex];
  const pending = active?.validation?.status === "pending" || snapshot.validation.status === "pending";

  useEffect(() => {
    const saver = debounceDraftSave(() => saveEventLaunchDraft(localStorage, controller), 700);
    const unsubscribe = controller.subscribe(() => { if (controller.getSnapshot().revision > 0) saver.schedule(); });
    return () => { unsubscribe(); saver.destroy(); };
  }, [controller]);

  const validateActive = async () => {
    if (active === undefined) return false;
    const result = await controller.validate({ scope: { address: active.address }, event: "submit", reveal: true });
    if (!result.isValid) { setMessage("Please fix the highlighted fields before continuing."); requestAnimationFrame(() => formRef.current?.querySelector<HTMLElement>("[aria-invalid='true'], .field-issues")?.focus()); }
    return result.isValid;
  };
  const go = async (index: number) => {
    if (index > currentIndex && !(await validateActive())) return;
    const target = wizard.stages[index];
    if (target !== undefined) controller.dispatch(nodeEvent("wizard:go", EVENT_LAUNCH_WIZARD_ADDRESS, { payload: target.id }));
    setMessage("");
  };
  const next = async () => { if (await validateActive()) { wizard.next(); setMessage(""); } };
  const submit = async (event: FormEvent) => { event.preventDefault(); const result = await controller.validate({ scope: "form", event: "submit", reveal: true }); if (result.isValid) { setPublished(structuredClone(snapshot.value) as EventLaunchValue); setMessage("Event payload is ready. Publishing remains application policy."); } else { setMessage("Please resolve the highlighted issues before publishing."); } };
  const smoke = () => controller.batch(() => {
    const entries: readonly [readonly (string | number)[], unknown][] = [
      [["launch", "basics", "identity", "title"], smokeTestValue.launch.basics.identity.title], [["launch", "basics", "identity", "slug"], smokeTestValue.launch.basics.identity.slug], [["launch", "basics", "accessModel"], "free"], [["launch", "review", "confirmation"], smokeTestValue.launch.review.confirmation], [["launch", "review", "termsAccepted"], true],
    ];
    entries.forEach(([path, payload]) => controller.dispatch({ name: "input", target: { kind: "field", path }, payload }));
  });
  const copy = active === undefined ? ["Event launch", ""] : stageCopy[active.id] ?? [active.id, ""];
  const visibleIssues = snapshot.validation.visibleIssues;
  return <main className="event-shell"><header className="event-hero"><div><span className="eyebrow">Canonical cross-adapter example</span><h1>Launch an event people remember.</h1><p>One framework-neutral Stages workflow, composed with idiomatic adapter bindings.</p></div><span className="adapter-badge">{adapter}</span></header><div className="event-layout"><form className="event-card" data-testid="event-launch-form" ref={formRef} onSubmit={submit} noValidate><ol className="wizard-progress" data-testid="wizard-progress" aria-label="Event launch progress">{wizard.stages.map((stage, index) => <li key={stage.id}><button type="button" data-testid={`wizard-stage-${stage.id}`} aria-current={stage.active ? "step" : undefined} disabled={pending} onClick={() => void go(index)}>{stage.id}</button></li>)}</ol><section className="stage-panel" aria-labelledby="stage-heading"><div className="stage-heading"><h2 id="stage-heading">{copy[0]}</h2><p>{copy[1]}</p></div>{visibleIssues.length > 0 && <section className="validation-summary" data-testid="validation-summary" aria-labelledby="validation-heading"><h3 id="validation-heading">Check these details</h3><ul>{visibleIssues.map((entry) => <li key={`${entry.id}-${entry.path.join(".")}`}>{entry.message ?? entry.code}</li>)}</ul></section>}{published !== undefined && <section className="published" data-testid="published-payload"><h3>Publish payload</h3><pre className="published-payload">{JSON.stringify(published, null, 2)}</pre></section>}{wizard.activeStage === "basics" && <BasicsStage />}{wizard.activeStage === "venue" && <VenueStage />}{wizard.activeStage === "streaming" && <StreamingStage />}{wizard.activeStage === "agenda" && <AgendaStage controller={controller} />}{wizard.activeStage === "tickets" && <TicketsStage controller={controller} value={snapshot.value as EventLaunchValue} />}{wizard.activeStage === "compliance" && <div className="field-grid"><Field path={["launch", "compliance", "dataProcessingAccepted"]} /></div>}{wizard.activeStage === "review" && <ReviewStage value={snapshot.value as EventLaunchValue} />}<p className="form-status" data-testid="form-status" role="status" aria-live="polite">{pending ? "Checking your details…" : message}</p><div className="stage-actions"><button type="button" className="secondary" disabled={!wizard.canPrevious || pending} onClick={wizard.previous}>Previous</button>{wizard.canNext ? <button type="button" className="primary" disabled={pending} onClick={() => void next()}>Next</button> : <button className="primary" type="submit" disabled={pending}>Publish event</button>}</div></section></form><aside className="summary-rail" aria-label="Event summary"><h2>Launch summary</h2><dl className="summary-list"><div><dt>Status</dt><dd>Draft</dd></div><div><dt>Current stage</dt><dd>{wizard.activeStage ?? "None"}</dd></div><div><dt>Visible stages</dt><dd>{wizard.stages.length}</dd></div><div><dt>Validation</dt><dd>{snapshot.validation.status}</dd></div></dl><div className="utility-actions"><button type="button" data-testid="apply-template" onClick={() => controller.dispatch(formEvent("apply-template"))}>Apply conference template</button><button type="button" data-testid="save-draft" onClick={() => { saveEventLaunchDraft(localStorage, controller); setMessage("Draft saved by the application."); }}>Save draft</button><button type="button" data-testid="resume-draft" disabled={localStorage.getItem(EVENT_LAUNCH_STORAGE_KEY) === null} onClick={() => { const saved = readEventLaunchDraft(localStorage); if (saved !== undefined) onResume(saved); }}>Resume draft</button><button type="button" data-testid="start-over" onClick={() => { controller.dispatch(formEvent("form:reset")); clearEventLaunchDraft(localStorage); setMessage("The accepted baseline was restored."); }}>Start over</button>{import.meta.env.DEV && <button type="button" onClick={smoke}>Load smoke-test data</button>}</div><label className="context-toggle"><input type="checkbox" checked={context.requiresDataProcessingAgreement} onChange={(event) => setContext({ ...context, requiresDataProcessingAgreement: event.currentTarget.checked })} />Require data-processing agreement</label><details className="inspector" data-testid="stages-inspector"><summary>Stages inspector</summary><pre>{JSON.stringify({ value: snapshot.value, validation: snapshot.validation, activeStage: wizard.activeStage, visibleStages: wizard.stages.map((stage) => stage.id), lastTransaction: lastChange === undefined ? null : { source: lastChange.source, events: lastChange.events.map((event) => event.name), patchCount: lastChange.patches.length, transactionId: lastChange.transactionId }, diagnostics: snapshot.diagnostics, envelope: controller.serialize() }, null, 2)}</pre></details></aside></div></main>;
}

export function EventLaunchApp({ adapter }: { readonly adapter: string }) {
  const [resume, setResume] = useState<{ readonly key: number; readonly state?: SerializedStagesState }>({ key: 0 });
  return <EventLaunchInner key={resume.key} adapter={adapter} initialState={resume.state} onResume={(state) => setResume(({ key }) => ({ key: key + 1, state }))} />;
}

// examples/angular/src/event-launch-app.ts
import { Component, computed, signal } from "@angular/core";
import { formEvent, nodeEvent, stages, type SerializedStagesState, type StagesChange, type StagesController } from "@stages/core";
import { StagesFieldComponent, collectionSignal, injectStages, wizardSignal } from "@stages/angular";
import { EVENT_LAUNCH_AGENDA_ADDRESS, EVENT_LAUNCH_STORAGE_KEY, clearEventLaunchDraft, createAgendaItem, createEventLaunchSchema, createTicketTier, defaultEventLaunchContext, defaultEventLaunchValue, eventLaunchValueCodec, readEventLaunchDraft, saveEventLaunchDraft, type AgendaItem, type EventLaunchContext, type EventLaunchValue } from "../../shared/event-launch/index.js";
import { eventLaunchAngularFields } from "./fields.js";

type Controller = StagesController<EventLaunchValue, typeof eventLaunchAngularFields, EventLaunchContext>;
const schema = createEventLaunchSchema();

@Component({
  selector: "stages-event-launch",
  standalone: true,
  imports: [StagesFieldComponent],
  template: `
    <main class="event-shell">
      <header class="event-hero"><div><span class="eyebrow">Canonical cross-adapter example</span><h1>Launch an event people remember.</h1><p>One framework-neutral Stages workflow, composed with idiomatic adapter bindings.</p></div><span class="adapter-badge">Angular</span></header>
      <div class="event-layout">
        <form class="event-card" data-testid="event-launch-form" (submit)="publish($event)">
          <ol class="wizard-progress" data-testid="wizard-progress" aria-label="Event launch progress">@for (stage of wizard().stages; track stage.id; let index = $index) { <li><button type="button" [attr.data-testid]="'wizard-stage-' + stage.id" [attr.aria-current]="stage.active ? 'step' : null" (click)="go(index)">{{ stage.id }}</button></li> }</ol>
          <section class="stage-panel" aria-labelledby="stage-heading">
            <div class="stage-heading"><h2 id="stage-heading">{{ stageTitle() }}</h2><p>Domain behavior is shared; this composition belongs to Angular signals.</p></div>
            @if (snapshot().validation.visibleIssues.length) { <section class="validation-summary" data-testid="validation-summary"><h3>Check these details</h3><ul>@for (issue of snapshot().validation.visibleIssues; track issue.id + issue.path.join('.')) { <li>{{ issue.message ?? issue.code }}</li> }</ul></section> }
            @if (published()) { <pre class="published-payload" data-testid="published-payload">{{ published() }}</pre> }
            @switch (wizard().activeStage) {
              @case ('basics') { <div class="field-grid"><stages-field [controller]="controller" [path]="['launch','basics','identity','title']"/><stages-field [controller]="controller" [path]="['launch','basics','identity','slug']"/><stages-field [controller]="controller" [path]="['launch','basics','identity','description']"/><stages-field [controller]="controller" [path]="['launch','basics','schedule','startsAt']"/><stages-field [controller]="controller" [path]="['launch','basics','schedule','endsAt']"/><stages-field [controller]="controller" [path]="['launch','basics','schedule','timezone']"/><stages-field [controller]="controller" [path]="['launch','basics','deliveryMode']"/><stages-field [controller]="controller" [path]="['launch','basics','accessModel']"/></div> }
              @case ('venue') { <div class="field-grid"><stages-field [controller]="controller" [path]="['launch','venue','name']"/><stages-field [controller]="controller" [path]="['launch','venue','capacity']"/><stages-field [controller]="controller" [path]="['launch','venue','address','street']"/><stages-field [controller]="controller" [path]="['launch','venue','address','city']"/><stages-field [controller]="controller" [path]="['launch','venue','address','country']"/><stages-field [controller]="controller" [path]="['launch','venue','accessibilityNotes']"/></div> }
              @case ('streaming') { <div class="field-grid"><stages-field [controller]="controller" [path]="['launch','streaming','platform']"/><stages-field [controller]="controller" [path]="['launch','streaming','url']"/><stages-field [controller]="controller" [path]="['launch','streaming','recordEvent']"/>@if (snapshot().value.launch.streaming.recordEvent) { <stages-field [controller]="controller" [path]="['launch','streaming','recordingConsent']"/> }</div> }
              @case ('agenda') { <div class="collection-toolbar"><strong>{{ agenda().items.length }} agenda items</strong><div class="row-actions"><button type="button" (click)="addAgenda('session')">Add session</button><button type="button" (click)="addAgenda('workshop')">Add workshop</button><button type="button" (click)="addAgenda('break')">Add break</button><button type="button" (click)="sortBreaksLast()">Sort breaks last</button></div></div><ol class="collection-list">@for (item of agenda().items; track item.key) { <li class="collection-row" [attr.data-testid]="'agenda-row-' + item.value.id"><div class="row-header"><span class="row-kind">{{ item.value.kind }}</span><span class="row-key">{{ item.key }}</span></div><div class="field-grid">@if (item.value.kind === 'break') { <stages-field [controller]="controller" [path]="['launch','agenda','items',item.index,'label']"/> } @else { <stages-field [controller]="controller" [path]="['launch','agenda','items',item.index,'title']"/> @if (item.value.kind === 'session') { <stages-field [controller]="controller" [path]="['launch','agenda','items',item.index,'speaker']"/> } @else { <stages-field [controller]="controller" [path]="['launch','agenda','items',item.index,'facilitator']"/> } }<stages-field [controller]="controller" [path]="['launch','agenda','items',item.index,'durationMinutes']"/>@if (item.value.kind === 'workshop') { <stages-field [controller]="controller" [path]="['launch','agenda','items',item.index,'capacity']"/> }</div><div class="row-actions"><button type="button" class="quiet" [disabled]="!item.canMovePrevious" (click)="item.moveTo(item.index - 1)">Move up</button><button type="button" class="quiet" [disabled]="!item.canMoveNext" (click)="item.moveTo(item.index + 1)">Move down</button><button type="button" class="quiet danger" [disabled]="!item.canRemove" (click)="item.remove()">Remove</button></div></li> }</ol> }
              @case ('tickets') { <div class="field-grid"><stages-field [controller]="controller" [path]="['launch','tickets','currency']"/></div><div class="collection-toolbar"><strong>{{ tickets().items.length }} ticket tiers</strong><button type="button" (click)="addTicket()">Add tier</button></div><ol class="collection-list">@for (item of tickets().items; track item.key) { <li class="collection-row" [attr.data-testid]="'ticket-row-' + item.value.id"><div class="field-grid"><stages-field [controller]="controller" [path]="['launch','tickets','tiers',item.index,'name']"/><stages-field [controller]="controller" [path]="['launch','tickets','tiers',item.index,'price']"/><stages-field [controller]="controller" [path]="['launch','tickets','tiers',item.index,'quantity']"/></div><div class="row-actions"><button type="button" class="quiet" [disabled]="!item.canMovePrevious" (click)="item.moveTo(item.index - 1)">Move up</button><button type="button" class="quiet danger" [disabled]="!item.canRemove" (click)="item.remove()">Remove</button></div></li> }</ol> }
              @case ('compliance') { <div class="field-grid"><stages-field [controller]="controller" [path]="['launch','compliance','dataProcessingAccepted']"/></div> }
              @case ('review') { <dl class="summary-list"><div><dt>Event</dt><dd>{{ snapshot().value.launch.basics.identity.title }}</dd></div><div><dt>Delivery</dt><dd>{{ snapshot().value.launch.basics.deliveryMode }}</dd></div></dl><div class="field-grid"><stages-field [controller]="controller" [path]="['launch','review','termsAccepted']"/><stages-field [controller]="controller" [path]="['launch','review','confirmation']"/></div> }
            }
            <p class="form-status" role="status" aria-live="polite" data-testid="form-status">{{ message() }}</p><div class="stage-actions"><button type="button" class="secondary" [disabled]="!wizard().canPrevious" (click)="wizard().previous()">Previous</button>@if (wizard().canNext) { <button type="button" class="primary" (click)="next()">Next</button> } @else { <button type="submit" class="primary">Publish event</button> }</div>
          </section>
        </form>
        <aside class="summary-rail"><h2>Launch summary</h2><dl class="summary-list"><div><dt>Current stage</dt><dd>{{ wizard().activeStage }}</dd></div><div><dt>Visible stages</dt><dd>{{ wizard().stages.length }}</dd></div><div><dt>Validation</dt><dd>{{ snapshot().validation.status }}</dd></div></dl><div class="utility-actions"><button type="button" data-testid="apply-template" (click)="applyTemplate()">Apply conference template</button><button type="button" data-testid="save-draft" (click)="save()">Save draft</button><button type="button" data-testid="resume-draft" [disabled]="!hasDraft()" (click)="resume()">Resume draft</button><button type="button" data-testid="start-over" (click)="startOver()">Start over</button></div><label class="context-toggle"><input type="checkbox" [checked]="context().requiresDataProcessingAgreement" (change)="toggleCompliance($event)"/>Require data-processing agreement</label><details class="inspector" data-testid="stages-inspector"><summary>Stages inspector</summary><pre>{{ inspector() }}</pre></details></aside>
      </div>
    </main>
  `,
})
export class EventLaunchAppComponent {
  readonly context = signal(defaultEventLaunchContext);
  readonly value = signal<EventLaunchValue>(structuredClone(defaultEventLaunchValue));
  readonly message = signal("");
  readonly published = signal<string | undefined>(undefined);
  readonly lastChange = signal<StagesChange<EventLaunchValue> | undefined>(undefined);
  private readonly restored: SerializedStagesState | undefined = sessionStorage.getItem("event-launch-resume") === "true" ? readEventLaunchDraft(localStorage) : undefined;
  readonly binding = injectStages(() => {
    sessionStorage.removeItem("event-launch-resume");
    let created: Controller;
    const onChange = (change: StagesChange<EventLaunchValue>) => { this.value.set(change.value); this.lastChange.set(change); };
    created = this.restored === undefined ? stages<EventLaunchValue, typeof eventLaunchAngularFields, EventLaunchContext>({ schema, fields: eventLaunchAngularFields, value: this.value(), context: this.context(), codec: eventLaunchValueCodec, onChange }) : stages<EventLaunchValue, typeof eventLaunchAngularFields, EventLaunchContext>({ schema, fields: eventLaunchAngularFields, state: this.restored, context: this.context(), codec: eventLaunchValueCodec, onChange });
    if (this.restored !== undefined) this.value.set(structuredClone(created.getSnapshot().value) as EventLaunchValue);
    return created;
  }, computed(() => ({ value: this.value(), context: this.context() })));
  readonly controller = this.binding.controller;
  readonly snapshot = this.binding.snapshot;
  readonly wizard = wizardSignal(this.controller, ["launch"]);
  readonly agenda = collectionSignal(this.controller, ["launch", "agenda", "items"] as const);
  readonly tickets = collectionSignal(this.controller, ["launch", "tickets", "tiers"] as const);
  readonly hasDraft = signal(localStorage.getItem(EVENT_LAUNCH_STORAGE_KEY) !== null);
  readonly stageTitle = computed(() => ({ basics: "Event basics", venue: "Venue", streaming: "Streaming", agenda: "Agenda", tickets: "Ticket tiers", compliance: "Data processing", review: "Review and publish" }[this.wizard().activeStage ?? ""] ?? "Event launch"));
  readonly inspector = computed(() => JSON.stringify({ value: this.snapshot().value, validation: this.snapshot().validation, activeStage: this.wizard().activeStage, visibleStages: this.wizard().stages.map((stage) => stage.id), lastTransaction: this.lastChange(), diagnostics: this.snapshot().diagnostics, envelope: this.controller.serialize() }, null, 2));
  private agendaId = 10; private ticketId = 10;
  private async validateActive(): Promise<boolean> { const active = this.wizard().stages.find((stage) => stage.active); if (active === undefined) return false; const result = await this.controller.validate({ scope: { address: active.address }, event: "submit", reveal: true }); if (!result.isValid) this.message.set("Please fix the highlighted fields before continuing."); return result.isValid; }
  async next(): Promise<void> { if (await this.validateActive()) this.wizard().next(); }
  async go(index: number): Promise<void> { const current = this.wizard().stages.findIndex((stage) => stage.active); const target = this.wizard().stages[index]; if (target !== undefined && (index <= current || await this.validateActive())) this.wizard().go(target.id); }
  async publish(event: Event): Promise<void> { event.preventDefault(); const result = await this.controller.validate({ scope: "form", event: "submit", reveal: true }); if (result.isValid) { this.published.set(JSON.stringify(this.snapshot().value, null, 2)); this.message.set("Event payload is ready. Publishing remains application policy."); } else this.message.set("Please resolve the highlighted issues before publishing."); }
  addAgenda(kind: AgendaItem["kind"]): void { this.agenda().add(createAgendaItem(kind, `agenda-${kind}-${this.agendaId}`)); this.agendaId += 1; }
  sortBreaksLast(): void { const order = this.agenda().items.map((item, index) => ({ index, break: item.value.kind === "break" })).sort((a, b) => Number(a.break) - Number(b.break)).map((entry) => entry.index); this.controller.dispatch(nodeEvent("collection:sort", EVENT_LAUNCH_AGENDA_ADDRESS, { payload: { order } })); }
  addTicket(): void { this.tickets().add(createTicketTier(`ticket-${this.ticketId}`)); this.ticketId += 1; }
  applyTemplate(): void { this.controller.dispatch(formEvent("apply-template")); }
  save(): void { saveEventLaunchDraft(localStorage, this.controller); this.hasDraft.set(true); this.message.set("Draft saved by the application."); }
  resume(): void { sessionStorage.setItem("event-launch-resume", "true"); location.reload(); }
  startOver(): void { this.controller.dispatch(formEvent("form:reset")); clearEventLaunchDraft(localStorage); this.hasDraft.set(false); }
  toggleCompliance(event: Event): void { if (event.currentTarget instanceof HTMLInputElement) this.context.update((context) => ({ ...context, requiresDataProcessingAgreement: event.currentTarget instanceof HTMLInputElement && event.currentTarget.checked })); }
}
